### PR TITLE
Rename "YOUR LAST RUNNED JOBS" to "RECENTLY EXECUTED JOBS" to improve…

### PR DESCRIPTION
**Pull request by virtualguy**
… readability

### CODE REVIEW

**Comment by Lothiraldan** [comment]
I'm sorry, I've had some unpushed commits that made the same change, do you think `LAST LAUNCHED JOBS` is better than `YOUR LAST RUNNED JOBS`?

**Comment by Lothiraldan** [comment]
I'm sorry, I've had some unpushed commits that made the same change, do you think `LAST LAUNCHED JOBS` is better than `YOUR LAST RUNNED JOBS`?

**Comment by virtualguy** [comment]
I'd say "RECENTLY LAUNCHED JOBS". Last doesn't quite sound right as only one job can the last job, but we really want it to be a list from newest to oldest. But i'm not to fussed either way.

**Comment by Lothiraldan** [comment]
The list contains only jobs launched by yourself through saltpad, so the name should reflect this specificity.

**Comment by colegatron** [comment]
When you say "jobs launched by yourself" do you mean "jobs launched by the external_auth user configured in salt master?". 
If it is I agree with  @virtualguy "Last executed jobs" fits better because the same user can be used from other scripts in the system.
Also looks more 'pro' than "your last runned jobs", imho

**Comment by Lothiraldan** [comment]
When I say "jobs launched by yourself", I mean the currently logged user in saltpad, when saltpad does a HTTP call to start a job I save the job id in a list and display the list of jobs under the "jobs launched by yourself" section.

**Pull request closed without merging**
